AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template - DynamoDB Table with Parameter Store
  Created by Theodor Harmse for University of Liverpool -
  Deploys a DynamoDB table and stores alias DNS, actual AWS regional endpoint,
  table name, and region in a single SecureString Parameter Store entry for API Service use.

Parameters:

  Region:
    Type: String
    Default: eu-west-1
    AllowedValues:
      - eu-west-1
      - eu-central-1
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
    Description: AWS Region for deployment

  HostedZoneDomainName:
    Type: String
    Default: liverpool.com
    Description: Base domain for the private hosted zone

  TableName:
    Type: String
    Default: transaction_records
    Description: DynamoDB table name

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Deployment Configuration
        Parameters:
          - Region
          - HostedZoneDomainName
          - TableName

Resources:

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: transaction_id
          AttributeType: S
      KeySchema:
        - AttributeName: transaction_id
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Name
          Value: !Ref TableName

  DynamoDBCredentialJson:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/Liverpool/DynamoDB/Credentials"
      Type: String
      Value: !Sub |
        {
          "alias": "dynamodb.${HostedZoneDomainName}",
          "endpoint": "https://dynamodb.${Region}.amazonaws.com",
          "table_name": "${TableName}",
          "region": "${Region}"
        }
      Description: "DynamoDB connection details for API Service in JSON format"

Outputs:

  DynamoDBTableName:
    Description: Name of the DynamoDB table
    Value: !Ref TableName

  ParameterStoreCredentialPath:
    Description: SSM Parameter Store path for JSON credentials
    Value: "/Liverpool/DynamoDB/Credentials"
