version: 0.0
os: linux

files:
  - source: api_service
    destination: /home/ec2-user/app/api_service
  - source: scripts
    destination: /home/ec2-user/app/scripts
  - source: requirements.txt
    destination: /home/ec2-user/app/requirements.txt

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root
