version: 0.0
os: linux

files:
  - source: api_service
    destination: /var/www/app/api_service
  - source: requirements.txt
    destination: /var/www/app
  - source: scripts
    destination: /var/www/app/scripts

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root
