version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing build dependencies
      - pip install --upgrade pip
  pre_build:
    commands:
      - echo Preparing artifacts for CodeDeploy
      - mkdir -p packaged/scripts
      - cp scripts/*.sh packaged/scripts/
      - cp appspec.yml packaged/
      - cp requirements.txt packaged/
      - cp -r *.py packaged/
  build:
    commands:
      - echo Build phase completed
  post_build:
    commands:
      - echo Packaging complete

artifacts:
  files:
    - '**/*'
  base-directory: packaged
