version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing build dependencies
      - pip install --upgrade pip

  pre_build:
    commands:
      - echo "Cleaning packaged directory"
      - rm -rf packaged
      - echo "Checking requirements.txt is a file"
      - if [ ! -f requirements.txt ]; then echo "ERROR: requirements.txt missing!"; exit 1; fi
      - echo "Preparing artifacts for CodeDeploy"
      - mkdir -p packaged/api_service
      - cp -r api_service/* packaged/api_service/
      - mkdir -p packaged/scripts
      - cp -r scripts/* packaged/scripts/
      - cp appspec.yml packaged/
      - cp requirements.txt packaged/

  build:
    commands:
      - echo Build phase complete

  post_build:
    commands:
      - echo Packaging complete

artifacts:
  files:
    - '**/*'
  base-directory: packaged
