version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - pip install -r requirements.txt --target ./package
  pre_build:
    commands:
      - echo Preparing artifact
      - mkdir -p package/api_service
      - cp -r api_service/* package/api_service/
      - mkdir -p package/scripts
      - cp -r scripts/* package/scripts/
      - cp appspec.yml package/
      - cp requirements.txt package/
  build:
    commands:
      - echo Build complete
  post_build:
    commands:
      - echo Packaging complete

artifacts:
  files:
    - '**/*'
  base-directory: package
