AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template - RDS IBM DB2 with Route53 and Parameter Store - Created by Theodor Harmse for University of Liverpool -
  Deploys an IBM DB2 RDS instance, creates a private Route 53 DNS record pointing to it, and stores the DNS name and credentials in Parameter Store.

Parameters:

  HostedZoneDomainName:
    Type: String
    Default: liverpool.com
    Description: Base domain for the private hosted zone

  Region:
    Type: String
    Default: eu-west-1
    AllowedValues:
      - eu-west-1
      - eu-central-1
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
    Description: AWS Region for deployment

  DBInstanceIdentifier:
    Type: String
    Default: liv-rds-DB2
    Description: The name for the RDS DB instance

  DBInstanceClass:
    Type: String
    Default: db.r6i.large
    AllowedValues:
      - db.r6i.large
      - db.m6i.large
      - db.r6i.xlarge
      - db.m6i.xlarge
    Description: RDS instance class

  DBName:
    Type: String
    Default: performance_db
    Description: Initial database name

  DBUsername:
    Type: String
    Default: adminuser
    Description: Master username

  DBPassword:
    Type: String
    NoEcho: true
    Default: Password123!
    Description: Master user password

  AllocatedStorage:
    Type: Number
    Default: 100
    Description: Allocated storage (GB)

  PreferredAvailabilityZone:
    Type: String
    Default: eu-west-1a
    Description: Preferred Availability Zone for the RDS instance

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Deployment Configuration
        Parameters:
          - Region
          - PreferredAvailabilityZone
          - HostedZoneDomainName
          - DBInstanceIdentifier
          - DBInstanceClass
          - AllocatedStorage
      - Label:
          default: Database Configuration
        Parameters:
          - DBName
          - DBUsername
          - DBPassword

Resources:

  DB2RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      Engine: db2
      EngineVersion: 11.5.9.0
      LicenseModel: license-included
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref AllocatedStorage
      StorageType: gp3
      StorageEncrypted: true
      AvailabilityZone: !Ref PreferredAvailabilityZone
      VPCSecurityGroups:
        - !ImportValue SecurityGroup-RDSSGId
      DBSubnetGroupName: !ImportValue DB-Subnet-Group-RDSSubnetGroupName
      MultiAZ: false
      PubliclyAccessible: false
      DeletionProtection: false
      BackupRetentionPeriod: 7
      Tags:
        - Key: Name
          Value: !Ref DBInstanceIdentifier

  IBMDB2RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue PrivateHostedZoneId
      Name: !Sub "ibmdb2.${HostedZoneDomainName}"
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - !GetAtt DB2RDSInstance.Endpoint.Address

  IBMDB2EndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/Liverpool/RDS/IBMDB2/Endpoint"
      Type: String
      Value: !Sub "ibmdb2.${HostedZoneDomainName}"
      Description: "IBM DB2 Private Hosted Zone DNS Name"

  IBMDB2UsernameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/Liverpool/RDS/IBMDB2/Username"
      Type: String
      Value: !Ref DBUsername
      Description: "IBM DB2 Admin Username"

  IBMDB2PasswordParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/Liverpool/RDS/IBMDB2/Password"
      Type: String
      Value: !Ref DBPassword
      Description: "IBM DB2 Admin Password"

  IBMDB2DatabaseNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/Liverpool/RDS/IBMDB2/DatabaseName"
      Type: String
      Value: !Ref DBName
      Description: "IBM DB2 Database Name"

Outputs:

  RDSInstanceEndpoint:
    Description: The endpoint address of the IBM DB2 RDS instance
    Value: !GetAtt DB2RDSInstance.Endpoint.Address
    Export:
      Name: RDS-DB2-Endpoint

  RDSInstanceId:
    Description: The ID of the IBM DB2 RDS instance
    Value: !Ref DB2RDSInstance
    Export:
      Name: RDS-DB2-InstanceId

  IBMDB2RecordName:
    Description: DNS name for IBM DB2 in Private Hosted Zone
    Value: !Sub "ibmdb2.${HostedZoneDomainName}"

  ParameterStoreEndpointName:
    Description: SSM Parameter Store key for the Endpoint
    Value: "/Liverpool/RDS/IBMDB2/Endpoint"
