AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template - Aurora MySQL Cluster with Route53 and Parameter Store - Created by Theodor Harmse for University of Liverpool -
  Deploys a single-instance Aurora MySQL cluster, creates a private Route 53 DNS record pointing to it, and stores the DNS name and credentials in Parameter Store.

Parameters:

  HostedZoneDomainName:
    Type: String
    Default: liverpool.com
    Description: Base domain for the private hosted zone

  Region:
    Type: String
    Default: eu-west-1
    AllowedValues:
      - eu-west-1
      - eu-central-1
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
    Description: AWS Region for deployment

  DBClusterIdentifier:
    Type: String
    Default: liv-aurora-cluster
    Description: The name for the Aurora DB cluster

  DBInstanceIdentifier:
    Type: String
    Default: liv-aurora-instance
    Description: The name for the Aurora DB instance

  DBInstanceClass:
    Type: String
    Default: db.r6i.large
    AllowedValues:
      - db.r6i.large
      - db.t3.medium
      - db.m6i.large
      - db.r6i.xlarge
      - db.m6i.xlarge
    Description: Aurora instance class

  DBName:
    Type: String
    Default: performance_db
    Description: Initial database name

  DBUsername:
    Type: String
    Default: adminuser
    Description: Master username

  DBPassword:
    Type: String
    NoEcho: true
    Default: Password123!
    Description: Master user password

  PreferredAvailabilityZone:
    Type: String
    Default: eu-west-1a
    Description: Preferred Availability Zone for the Aurora instance

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Deployment Configuration
        Parameters:
          - Region
          - PreferredAvailabilityZone
          - HostedZoneDomainName
          - DBClusterIdentifier
          - DBInstanceIdentifier
          - DBInstanceClass
      - Label:
          default: Database Configuration
        Parameters:
          - DBName
          - DBUsername
          - DBPassword

Resources:

  AuroraDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
      EngineVersion: 8.0.mysql_aurora.3.04.0
      DBClusterIdentifier: !Ref DBClusterIdentifier
      DatabaseName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      VpcSecurityGroupIds:
        - !ImportValue SecurityGroup-RDSSGId
      DBSubnetGroupName: !ImportValue DB-Subnet-Group-RDSSubnetGroupName
      BackupRetentionPeriod: 7
      PreferredBackupWindow: 03:00-04:00
      DeletionProtection: false
      StorageEncrypted: true
      Tags:
        - Key: Name
          Value: !Ref DBClusterIdentifier

  AuroraDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBClusterIdentifier: !Ref AuroraDBCluster
      Engine: aurora-mysql
      DBInstanceClass: !Ref DBInstanceClass
      AvailabilityZone: !Ref PreferredAvailabilityZone
      PubliclyAccessible: false
      Tags:
        - Key: Name
          Value: !Ref DBInstanceIdentifier

  AuroraMySQLRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue PrivateHostedZoneId
      Name: !Sub "auroramysql.${HostedZoneDomainName}"
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - !GetAtt AuroraDBCluster.Endpoint.Address

  AuroraMySQLEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/Liverpool/RDS/AuroraMySQL/Endpoint"
      Type: String
      Value: !Sub "auroramysql.${HostedZoneDomainName}"
      Description: "Aurora MySQL Private Hosted Zone DNS Name"

  AuroraMySQLUsernameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/Liverpool/RDS/AuroraMySQL/Username"
      Type: String
      Value: !Ref DBUsername
      Description: "Aurora MySQL Admin Username"

  AuroraMySQLPasswordParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/Liverpool/RDS/AuroraMySQL/Password"
      Type: String
      Value: !Ref DBPassword
      Description: "Aurora MySQL Admin Password"

  AuroraMySQLDatabaseNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/Liverpool/RDS/AuroraMySQL/DatabaseName"
      Type: String
      Value: !Ref DBName
      Description: "Aurora MySQL Database Name"

Outputs:

  AuroraClusterEndpoint:
    Description: The endpoint of the Aurora cluster
    Value: !GetAtt AuroraDBCluster.Endpoint.Address
    Export:
      Name: Aurora-MySQL-ClusterEndpoint

  AuroraClusterId:
    Description: The ID of the Aurora cluster
    Value: !Ref AuroraDBCluster
    Export:
      Name: Aurora-MySQL-ClusterId

  AuroraInstanceId:
    Description: The ID of the Aurora instance
    Value: !Ref AuroraDBInstance
    Export:
      Name: Aurora-MySQL-InstanceId

  AuroraMySQLRecordName:
    Description: DNS name for Aurora MySQL in Private Hosted Zone
    Value: !Sub "auroramysql.${HostedZoneDomainName}"

  ParameterStoreEndpointName:
    Description: SSM Parameter Store key for the Endpoint
    Value: "/Liverpool/RDS/AuroraMySQL/Endpoint"
