AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template - RDS PostgreSQL with Route53 and Parameter Store - Created by Theodor Harmse for University of Liverpool -
  Deploys a PostgreSQL RDS instance, creates a private Route 53 DNS record pointing to it, and stores the DNS name and credentials in Parameter Store.

Parameters:

  HostedZoneDomainName:
    Type: String
    Default: liverpool.com
    Description: Base domain for the private hosted zone

  Region:
    Type: String
    Default: eu-west-1
    AllowedValues:
      - eu-west-1
      - eu-central-1
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
    Description: AWS Region for deployment

  DBInstanceIdentifier:
    Type: String
    Default: liv-rds-PostgreSQL
    Description: The name for the RDS DB instance

  DBInstanceClass:
    Type: String
    Default: db.r6i.large
    AllowedValues:
      - db.r6i.large
      - db.t3.medium
      - db.m6i.large
      - db.r6i.xlarge
      - db.m6i.xlarge
    Description: RDS instance class

  DBName:
    Type: String
    Default: performance_db
    Description: Initial database name

  DBUsername:
    Type: String
    Default: adminuser
    Description: Master username

  DBPassword:
    Type: String
    NoEcho: true
    Default: Password123!
    Description: Master user password

  AllocatedStorage:
    Type: Number
    Default: 20
    Description: Allocated storage (GB)

  PreferredAvailabilityZone:
    Type: String
    Default: eu-west-1a
    Description: Preferred Availability Zone for the RDS instance

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Deployment Configuration
        Parameters:
          - Region
          - PreferredAvailabilityZone
          - HostedZoneDomainName
          - DBInstanceIdentifier
          - DBInstanceClass
          - AllocatedStorage
      - Label:
          default: Database Configuration
        Parameters:
          - DBName
          - DBUsername
          - DBPassword

Resources:

  PostgreSQLRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBName: !Ref DBName
      Engine: postgres
      EngineVersion: 17.5
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref AllocatedStorage
      StorageType: gp3
      StorageEncrypted: true
      AvailabilityZone: !Ref PreferredAvailabilityZone
      VPCSecurityGroups:
        - !ImportValue SecurityGroup-RDSSGId
      DBSubnetGroupName: !ImportValue DB-Subnet-Group-RDSSubnetGroupName
      MultiAZ: false
      PubliclyAccessible: false
      DeletionProtection: false
      BackupRetentionPeriod: 7
      Tags:
        - Key: Name
          Value: !Ref DBInstanceIdentifier

  PostgreSQLRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue PrivateHostedZoneId
      Name: !Sub "postgresql.${HostedZoneDomainName}"
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - !GetAtt PostgreSQLRDSInstance.Endpoint.Address

  PostgreSQLEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/Liverpool/RDS/PostgreSQL/Endpoint"
      Type: String
      Value: !Sub "postgresql.${HostedZoneDomainName}"
      Description: "PostgreSQL Private Hosted Zone DNS Name"

  PostgreSQLUsernameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/Liverpool/RDS/PostgreSQL/Username"
      Type: String
      Value: !Ref DBUsername
      Description: "PostgreSQL Admin Username"

  PostgreSQLPasswordParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/Liverpool/RDS/PostgreSQL/Password"
      Type: String
      Value: !Ref DBPassword
      Description: "PostgreSQL Admin Password"

  PostgreSQLDatabaseNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/Liverpool/RDS/PostgreSQL/DatabaseName"
      Type: String
      Value: !Ref DBName
      Description: "PostgreSQL Database Name"

Outputs:

  RDSInstanceEndpoint:
    Description: The endpoint address of the PostgreSQL RDS instance
    Value: !GetAtt PostgreSQLRDSInstance.Endpoint.Address
    Export:
      Name: RDS-PostgreSQL-Endpoint

  RDSInstanceId:
    Description: The ID of the PostgreSQL RDS instance
    Value: !Ref PostgreSQLRDSInstance
    Export:
      Name: RDS-PostgreSQL-InstanceId

  PostgreSQLRecordName:
    Description: DNS name for PostgreSQL in Private Hosted Zone
    Value: !Sub "postgresql.${HostedZoneDomainName}"

  ParameterStoreEndpointName:
    Description: SSM Parameter Store key for the Endpoint
    Value: "/Liverpool/RDS/PostgreSQL/Endpoint"
