AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template - RDS MySQL with Route53 and Parameter Store - Created by Theodor Harmse for University of Liverpool -
  Deploys a MySQL RDS instance, creates a Route 53 private DNS record pointing to it, and stores the DNS name, username, and password in Parameter Store.

Parameters:

  HostedZoneDomainName:
    Type: String
    Default: liverpool.com
    Description: Base domain for the private hosted zone

  Region:
    Type: String
    Default: eu-west-1
    AllowedValues:
      - eu-west-1
      - eu-central-1
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
    Description: AWS Region for deployment

  DBInstanceIdentifier:
    Type: String
    Default: liv-rds-MySQL
    Description: The name for the RDS DB instance

  DBInstanceClass:
    Type: String
    Default: db.r6i.large
    AllowedValues:
      - db.r6i.large
      - db.t3.medium
      - db.m6i.large
      - db.r6i.xlarge
      - db.m6i.xlarge
    Description: RDS instance class

  DBName:
    Type: String
    Default: performance_db
    Description: Initial database name

  DBUsername:
    Type: String
    Default: adminuser
    Description: Master username

  DBPassword:
    Type: String
    NoEcho: true
    Default: Password123!
    Description: Master user password

  AllocatedStorage:
    Type: Number
    Default: 20
    Description: Allocated storage (GB)

  PreferredAvailabilityZone:
    Type: String
    Default: eu-west-1a
    Description: Preferred Availability Zone for the RDS instance

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Deployment Configuration
        Parameters:
          - Region
          - PreferredAvailabilityZone
          - HostedZoneDomainName
          - DBInstanceIdentifier
          - DBInstanceClass
          - AllocatedStorage
      - Label:
          default: Database Configuration
        Parameters:
          - DBName
          - DBUsername
          - DBPassword

Resources:

  MySQLRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBName: !Ref DBName
      Engine: mysql
      EngineVersion: 8.0.42
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref AllocatedStorage
      StorageType: gp3
      StorageEncrypted: true
      AvailabilityZone: !Ref PreferredAvailabilityZone
      VPCSecurityGroups:
        - !ImportValue SecurityGroup-RDSSGId
      DBSubnetGroupName: !ImportValue DB-Subnet-Group-RDSSubnetGroupName
      MultiAZ: false
      PubliclyAccessible: false
      DeletionProtection: false
      BackupRetentionPeriod: 7
      Tags:
        - Key: Name
          Value: !Ref DBInstanceIdentifier

  MySQLRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue PrivateHostedZoneId
      Name: !Sub "mysql.${HostedZoneDomainName}"
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - !GetAtt MySQLRDSInstance.Endpoint.Address

  MySQLEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/Liverpool/RDS/MySQL/Endpoint"
      Type: String
      Value: !Sub "mysql.${HostedZoneDomainName}"
      Description: "MySQL Private Hosted Zone DNS Name"

  MySQLUsernameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/Liverpool/RDS/MySQL/Username"
      Type: String
      Value: !Ref DBUsername
      Description: "MySQL Admin Username"

  MySQLPasswordParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/Liverpool/RDS/MySQL/Password"
      Type: String
      Value: !Ref DBPassword
      Description: "MySQL Admin Password"

  MySQLDatabaseNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/Liverpool/RDS/MySQL/DatabaseName"
      Type: String
      Value: !Ref DBName
      Description: "MySQL Database Name"

Outputs:

  RDSInstanceEndpoint:
    Description: The endpoint address of the RDS instance
    Value: !GetAtt MySQLRDSInstance.Endpoint.Address
    Export:
      Name: RDS-MySQL-Endpoint

  RDSInstanceId:
    Description: The ID of the RDS instance
    Value: !Ref MySQLRDSInstance
    Export:
      Name: RDS-MySQL-InstanceId

  MySQLRecordName:
    Description: DNS name for MySQL in Private Hosted Zone
    Value: !Sub "mysql.${HostedZoneDomainName}"

  ParameterStoreEndpointName:
    Description: SSM Parameter Store key for the Endpoint
    Value: "/Liverpool/RDS/MySQL/Endpoint"
